---
downloads: ~/.ansible-downloads

configure_osx: true
osx_script: "~/.osx --no-restart"

configure_firefox: true
configure_slack: true
configure_vscode: true

configure_dotfiles: true
dotfiles_repo: https://github.com/david-oliver/dotfiles.git
dotfiles_repo_version: main
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/Code/dotfiles
dotfiles_files:
  - .bashrc
  - .bash_profile
  - .git-completion.bash
  - .osx
  - .gitconfig

homebrew_installed_packages:
  - act
  - awscli
  - azure-cli
  - bash
  - bash-completion@2
  - bash-git-prompt
  - ca-certificates
  - cffi
  - docutils
  - docker-completion
  - dockutil
  - dosbox
  - gdbm
  - gettext
  - git
  - go
  - golangci-lint
  - jq
  - libyaml
  - libogg
  - libpng
  - libvorbis
  - mpdecimal
  - oniguruma
  - openssl@3
  - packer
  - p7zip
  - pcre2
  - pre-commit
  - pycparser
  - python-certifi
  - python-cryptography
  - python-lxml
  - python-markupsafe
  - python-packaging
  - python-pytz
  - python-setuptools
  - pyyaml
  - readline
  - sdl12-compat
  - sdl2
  - sdl_net
  - sdl_sound
  - six
  - sqlite
  - stella
  - terraform
  - virtualenv
  - xcodegen
  - xz
  - yamllint
  - yq

homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - android-platform-tools
  - chromedriver
  - deluge
  - docker
  - firefox
  - google-chrome
  - google-cloud-sdk
  - insomnia
  - intellij-idea
  - iterm2
  - libreoffice
  - openlens
  - signal
  - slack
  - spotify
  - vlc
  - vscodium
  - zoom

configure_dock: true
dockitems_remove:
  - Launchpad
  - Safari
  - Messages
  - Mail
  - Maps
  - Photos
  - FaceTime
  - Contacts
  - Reminders
  - Notes
  - Freeform
  - TV
  - Music
  - News
  - "App Store"
dockitems_persist:
  - name: Firefox
    path: /Applications/Firefox.app/
    pos: 1
  - name: iTerm
    path: /Applications/iTerm.app/
    pos: 2
  - name: VSCodium
    path: /Applications/VSCodium.app/
    pos: 3
  - name: Slack
    path: /Applications/Slack.app/
    pos: 4
  - name: Signal
    path: /Applications/Signal.app/
    pos: 5
