---
downloads: ~/.ansible-downloads

configure_dotfiles: true

dotfiles_repo: https://github.com/david-oliver/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/Code/dotfiles
dotfiles_files:
  - .bashrc
  - .git-completion.bash

homebrew_installed_packages:
  - act
  - awscli
  - azure-cli
  - bash
  - bash-completion@2
  - bash-git-prompt
  - ca-certificates
  - cffi
  - docutils
  - docker-completion
  - dosbox
  - gdbm
  - gettext
  - git
  - go
  - golangci-lint
  - jq
  - libyaml
  - libogg
  - libpng
  - libvorbis
  - mpdecimal
  - oniguruma
  - openssl@3
  - packer
  - p7zip
  - pcre2
  - pre-commit
  - pycparser
  - python-certifi
  - python-cryptography
  - python-lxml
  - python-markupsafe
  - python-packaging
  - python-pytz
  - python-setuptools
  - pyyaml
  - readline
  - sdl12-compat
  - sdl2
  - sdl_net
  - sdl_sound
  - six
  - sqlite
  - stella
  - terraform
  - virtualenv
  - xcodegen
  - xz
  - yq

homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - android-platform-tools
  - chromedriver
  - deluge
  - docker
  - firefox
  - google-chrome
  - google-cloud-sdk
  - insomnia
  - intellij-idea
  - iterm2
  - libreoffice
  - openlens
  - signal
  - slack
  - spotify
  - vlc
  - vscodium
  - zoom