---
downloads: ~/.ansible-downloads

configure_osx: true
osx_script: "~/.osx --no-restart"

configure_firefox: true
configure_slack: true
configure_vscode: true
configure_cis: true

configure_mouse: true

configure_sudoers: false
sudoers_custom_config: |
  # Allow users in admin group to use sudo with no password.
  %admin ALL=(ALL) NOPASSWD: ALL

configure_dotfiles: true
dotfiles_repo: https://github.com/david-oliver/dotfiles.git
dotfiles_repo_version: main
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/Code/dotfiles
dotfiles_files:
  - name: .bashrc
    mode: '640'
  - name: .bash_profile
    mode: '640'
  - name: .git-completion.bash
    mode: '640'
  - name: .osx
    mode: '750'
  - name: .gitconfig
    mode: '640'
  - name: .ssh/config
    mode: '600'
  - name: .ssh/environments.d/
    mode: '700'
  - name: .ssh/environments.d/github
    mode: '600'
  - name: .aws/
    mode: '700'
  - name: .aws/config
    mode: '600'
  - name: .aws/credentials
    mode: '600'

homebrew_installed_packages:
  - act
  - awscli
  - azure-cli
  - bash
  - bash-completion@2
  - bash-git-prompt
  - ca-certificates
  - cffi
  - colima
  - container-diff
  - docutils
  - docker-completion
  - docker-compose 
  - docker-credential-helper 
  - docker-credential-helper-ecr
  - docker-slim
  - dockutil
  - dosbox
  - driftctl
  - gdbm
  - gettext
  - git
  - go
  - golangci-lint
  - infracost
  - jq
  - libyaml
  - libogg
  - libpng
  - libvorbis
  - localstack
  - mpdecimal
  - nvm
  - oniguruma
  - openssl@3
  - packer
  - p7zip
  - pcre2
  - pre-commit
  - pycparser
  - pyenv
  - python-certifi
  - python-cryptography
  - python-lxml
  - python-markupsafe
  - python-packaging
  - python-pytz
  - python-setuptools
  - pyyaml
  - readline
  - sdl12-compat
  - sdl2
  - sdl_net
  - sdl_sound
  - six
  - sqlite
  - stella
  - terraform
  - terraform-docs
  - terraform-local
  - terraform-ls
  - terrascan
  - thefuck
  - tflint
  - trivy
  - virtualenv
  - xcodegen
  - xz
  - yamllint
  - yq

homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - android-platform-tools
  - chromedriver
  - datagrip
  - deluge
  - docker
  - firefox
  - google-chrome
  - google-cloud-sdk
  - insomnia
  - intellij-idea
  - iterm2
  - libreoffice
  - maccy
  - openlens
  - pgadmin4
  - pritunl
  - pycharm
  - signal
  - slack
  - spotify
  - vlc
  - visual-studio-code
  - webstorm
  - zoom

configure_dock: true
dockitems_remove:
  - Launchpad
  - Safari
  - Messages
  - Mail
  - Maps
  - Photos
  - FaceTime
  - Contacts
  - Reminders
  - Notes
  - Freeform
  - TV
  - Music
  - News
  - Podcasts
  - Keynote
  - Numbers
  - Pages
  - "App Store"
dockitems_persist:
  - name: Firefox
    path: /Applications/Firefox.app/
    pos: 1
  - name: iTerm
    path: /Applications/iTerm.app/
    pos: 2
  - name: VSCodium
    path: "/Applications/Visual Studio Code.app/"
    pos: 3
  - name: Slack
    path: /Applications/Slack.app/
    pos: 4
  - name: Signal
    path: /Applications/Signal.app/
    pos: 5

configure_node: true
npm_packages: []

configure_python: true
pyenv_env: 'user'
pyenv_owner_group: 'staff'
pyenv_global:
  - "3.11.6"
pyenv_python_versions:
  - "3.11.6"
  - "3.10.13"
  - "3.9.18"
pyenv_virtualenvs:
  - venv_name: latest_v311
    py_version: 3.11.6
  - venv_name: latest_v310
    py_version: 3.10.13
  - venv_name: latest_v39
    py_version: 3.9.18
pip_packages: 
  - yawsso
  - cf2tf
