---
- name: Configure host.
  hosts: all

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: Include playbook configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']

  roles:
    - role: elliotweiser.osx-command-line-tools
    - role: geerlingguy.mac.homebrew
      tags: ['homebrew']
    - role: geerlingguy.dotfiles
      when: configure_dotfiles
      tags: ['dotfiles']
    - role: geerlingguy.mac.mas
      when: mas_installed_apps or mas_installed_app_ids
      tags: ['mas']
    - role: geerlingguy.mac.dock
      when: configure_dock
      tags: ['dock']

  homebrew_installed_packages:
    - act
    - awscli
    - azure-cli
    - ca-certificates
    - cffi
    - docutils
    - dosbox
    - gdbm
    - gettext
    - git
    - go
    - golangci-lint
    - jq
    - libyaml
    - libogg
    - libpng
    - libvorbis
    - mpdecimal
    - oniguruma
    - openssl@3
    - p7zip
    - pcre2
    - pre-commit
    - pycparser
    - python-certificates
    - python-cryptography
    - python-lxml
    - python-markupsafe
    - python-packaging
    - python-pytz
    - python-setuptools
    - pyyaml
    - readline
    - sdl12-compat
    - sdl2
    - sdl_net
    - sdl_sound
    - six
    - sqlite
    - stella
    - terraform
    - virtualenv
    - xcodegen
    - xz
    - yq

  homebrew_taps:
    - homebrew/core
    - homebrew/cask

  homebrew_cask_appdir: /Applications
  homebrew_cask_apps:
    - android-platform-tools
    - balena-etcher
    - chromedriver
    - deluge
    - docker
    - firefox
    - google-chrome
    - google-cloud-sdk
    - insomnia
    - intellij-idea
    - iterm2
    - libreoffice
    - openlens
    - signal
    - slack
    - spotify
    - vlc
    - vscodium
    - zoom
