---
- name: Configure host.
  hosts: all

  vars_files:
    - default_config.yml

  pre_tasks:
    - name: Include playbook configuration.
      ansible.builtin.include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']

  roles:
    - role: elliotweiser.osx-command-line-tools
    - role: geerlingguy.mac.homebrew
      tags: ['homebrew']
    - role: dotfiles
      when: configure_dotfiles
      tags: ['dotfiles']
    - role: geerlingguy.mac.dock
      when: configure_dock
      tags: ['dock']
    - role: staticdev.pyenv
      when: configure_python
      tags: ['python']

  tasks:
    - name: Configure mouse
      ansible.builtin.import_tasks: tasks/mouse.yml
      when: configure_mouse
      tags: ['mouse']
    - name: Configure OSX
      ansible.builtin.import_tasks: tasks/osx.yml
      when: configure_osx
      tags: ['osx']
    - name: Configure Firefox
      ansible.builtin.import_tasks: tasks/firefox.yml
      when: configure_firefox
      tags: ['firefox']
    - name: Configure Slack
      ansible.builtin.import_tasks: tasks/slack.yml
      when: configure_slack
      tags: ['slack']
    - name: Configure VSCode
      ansible.builtin.import_tasks: tasks/vscode.yml
      when: configure_vscode
      tags: ['vscode']
    - name: Run CIS Changes
      ansible.builtin.import_tasks: tasks/cis.yml
      when: configure_cis
      tags: ['cis']
    - name: Configure NodeJS
      ansible.builtin.import_tasks: tasks/node.yml
      when: configure_node
      tags: ['node']
    - name: Configure Python
      ansible.builtin.import_tasks: tasks/python.yml
      when: configure_python
      tags: ['python']
