---
- name: Configure host.
  hosts: all

  vars_files:
    - default_config.yml

  pre_tasks:
    - name: Include playbook configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']

  roles:
    - role: elliotweiser.osx-command-line-tools
    - role: geerlingguy.mac.homebrew
      tags: ['homebrew']
    - role: geerlingguy.dotfiles
      when: configure_dotfiles
      tags: ['dotfiles']
    - role: geerlingguy.mac.dock
      when: configure_dock
      tags: ['dock']

  tasks:
    - import_tasks: tasks/osx.yml
      when: configure_osx
      tags: ['osx']
    - import_tasks: tasks/firefox.yml
      when: configure_firefox
      tags: ['firefox']
    - import_tasks: tasks/slack.yml
      when: configure_slack
      tags: ['slack']
    - import_tasks: tasks/vscode.yml
      when: configure_vscode
      tags: ['vscode']
