---
- name: Ensure dotfiles repository is cloned locally.
  ansible.builtin.git:
    repo: "{{ dotfiles_repo }}"
    dest: "{{ dotfiles_repo_local_destination }}"
    version: "{{ dotfiles_repo_version }}"
    accept_hostkey: "{{ dotfiles_repo_accept_hostkey }}"
  become: false

- name: Check which dotfiles already exist.
  ansible.builtin.command: "ls -F {{ dotfiles_home }}/{{ item.name }}"
  register: existing_dotfile_info
  failed_when: false
  check_mode: false
  changed_when: false
  with_items: "{{ dotfiles_files }}"

- name: Remove existing dotfiles file if a replacement available.
  ansible.builtin.file:
    path: "{{ dotfiles_home }}/{{ dotfiles_files[item.0] }}"
    state: absent
  with_indexed_items: "{{ existing_dotfile_info.results }}"

- name: Copy dotfiles into home folder.
  ansible.builtin.copy:
    src: "{{ dotfiles_repo_local_destination }}/{{ item.name }}"
    dest: "{{ dotfiles_home }}/{{ item.name }}"
    mode: "{{ item.mode }}"
  become: false
  with_items: "{{ dotfiles_files }}"
